@extends('layouts.app')

@section('title', 'Absentees')

@section('content')
    <h1>Absentees</h1>
        <p><a href="{{ route('teacher.dashboard', [], false) }}">Dashboard</a></p>

            @if (! $teacher)
                    <p style="color: red;">Aapke account se koi teacher record linked nahi hai.</p>
                        @elseif (count($classes) === 0)
                                <p style="color: red;">Aapko koi class assign nahi hai.</p>
                                    @else
                                            <form method="GET" action="{{ route('teacher.absentees', [], false) }}">
                                                        <label>Class
                                                                        <select name="class">
                                                                                            @foreach ($classes as $c)
                                                                                                                    <option value="{{ $c }}" @selected($c === $class)>{{ $c }}</option>
                                                                                                                                        @endforeach
                                                                                                                                                        </select>
                                                                                                                                                                    </label>
                                                                                                                                                                                <label>Tareekh
                                                                                                                                                                                                <input type="date" name="date" value="{{ $date }}">
                                                                                                                                                                                                            </label>
                                                                                                                                                                                                                        <button type="submit">Dekhein</button>
                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                        @if ($noRecord)
                                                                                                                                                                                                                                                    <p>Is din is class ka koi attendance record nahi hai.</p>
                                                                                                                                                                                                                                                            @elseif ($absentees->isEmpty())
                                                                                                                                                                                                                                                                        <p>Koi absent student nahi mila.</p>
                                                                                                                                                                                                                                                                                @else
                                                                                                                                                                                                                                                                                            <h2>{{ $absentees->count() }} absent</h2>
                                                                                                                                                                                                                                                                                                        <ul>
                                                                                                                                                                                                                                                                                                                        @foreach ($absentees as $s)
                                                                                                                                                                                                                                                                                                                                            @php
                                                                                                                                                                                                                                                                                                                                                                    $digits = preg_replace('/\D/', '', (string) $s->guardian_phone);
                                                                                                                                                                                                                                                                                                                                                                                            if (str_starts_with($digits, '0')) {
                                                                                                                                                                                                                                                                                                                                                                                                                        $digits = '92' . substr($digits, 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $text = 'Assalam o Alaikum, ' . $s->name . ' aaj (' . $date . ') school mein absent tha/thi. - GBLSS Garho';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @endphp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {{ $s->name }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @if ($digits !== '')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            - <a href="https://wa.me/{{ $digits }}?text={{ rawurlencode($text) }}" target="_blank" rel="noopener noreferrer">WhatsApp</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                - (guardian ka number nahi hai)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @endif
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @endforeach
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @endif
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @endif
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @endsection